name: 02 - Workflow Events

# on:
#   - push
#   - pull_request
on:
  push:
  pull_request:
  schedule:
    # Every 5minutes CRON schedule
    - cron: "*/5 * * * *"
    # manual trigger from UI
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the triger
        run: echo "I have neen triggered by a(n) ${{github.event_name}} event"
