name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # 0 Checkout code fro m the repo **VERY IMPORTANT
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls

    # 1. Install deps of our React Application
    # 2. Execute Automated test
