name: 04 - Using Actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    # use defaults when we have many use case for it
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      # 0 Checkout code fro m the repo **VERY IMPORTANT
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      # 1. Install deps of our React Application
      - name: Install Dependencies
        run: npm ci
        # working-directory: 04-using-actions/react-app

    # 2. Execute Automated test
