name: 08 - Using Variables

on:
  push:
  workflow_dispatch:
env:
  WORKFLOW_VAR: "I am a workflow env var"
  OVERWRITTEN: "I will be overwritten"

jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: "I am ajob env var"
      OVERWRITTEN: "I have been overwritten at the job level"
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "I am as step env var"
          step_var2: "I am another step env var"
        run: |
          echo "Step env vars ${{env.STEP_VAR }}"
          echo "Step env var2: $step_var2"
          echo  "Job env var: ${{env.JOB_ENV}}"
          echo  "Workflow env var: ${{env.WORKFLOW_VAR}}"
          echo "Overwritten ${{env.OVERWRITTEN}}"
