name: 11 - Working with Inputs

on:
  # workflow_call are for allowing reusable workflow
  # Below are the 3 types of input when running a workflow dispatch
  #   if we use workflow_call we only few ones environment and
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        description: Skip Deployment and only print build ouput
        default: false
      target:
        type: environment
        required: true
        description: Which environment the workflow will target
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: Release from which to build and deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building from tag ${{inputs.tag}}"
  deploy:
    runs-on: ubuntu-latest
    if: ${{!inputs.dry-run}}
    environment: ${{inputs.target}}
    steps:
      - name: Deploy
        run: echo "Deploying to  ${{inputs.target}}"
